services:
  pg:
    image: bitnami/postgresql:17.4.0
    container_name: hexagonalDb
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hexagonalDb
    ports:
      - '5432:5432'
